### ISSUE TITLE
lb-ng command does not inject access_token in lb-services.js factories changeStream

### ISSUE THREAD

**Issue by SinvalMAO** [strongloop/loopback-sdk-angular#233] opened 2016-08-12 00:20 UTC
When activated acls to restrict access to types of users and methods, the lb-services.js has already injected access tokens to be able to work on the front end with angular loopback sdk, however for methods changeStream these tokens are not injected so generating a {"error": "no response from server"}, I found a solution that is rescuing the accessToken of credentials in localStorage and set as follows: **[var changeStreamUrl = '/api/Events/change-stream?_format=event-source&access_token=' + accessToken]**, however not found scaleable.

**Comment by davidcheung** [comment] 2016-09-02 18:53
Hi @SinvalMAO, thanks for bringing this up, do you know if the accessToken is available thru the headers, I believe they should be https://github.com/strongloop/loopback-sdk-angular/blob/1bf6f10ad47b04900a49a967217da60c9c7bba35/lib/services.template.ejs#L375, but maybe it did not properly propagate down. 
Would you be able to [fork a loopback-sandbox](https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report) to help reproduce this bug?

**Comment by bajtos** [comment] 2017-06-07 13:15
I am closing this issue because it's not clear how to reproduce it.

**Closed by bajtos** 2017-06-07 13:15 UTC
Labels: triaging
