### ISSUE TITLE
Strongloop exposing "_id" attribute to only the users owning the object 

### ISSUE THREAD

**Issue by iamdeadman** [strongloop/loopback-sdk-angular#204] opened 2016-01-14 21:29 UTC
I have a couple of models(Tuition, Tutor) and my tuition.json model definition file is as attacked
Now, I am trying to call Tuition.applicant.create() but the call "Tuition.find" does not return any id's for the user which did not create the object. So, how can I achieve this

[models.zip](https://github.com/strongloop/loopback-sdk-angular/files/91028/models.zip)

**Comment by richardpringle** [comment] 2016-05-11 13:03
Hey @iamdeadman, the best places for questions are as follows:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

I am not quite sure what you are trying to do here. Might be best if you fork a [loopback-sandbox](https://github.com/strongloop/loopback-sandbox) with the steps to reproduce your issue in the readme. In this case, it would also be good to provide your *desired outcome* in the readme as well and maybe we can help you get there... unless you found a bug :cold_sweat:. In the case you found a bug, we should be able to fix it!

**Comment by bajtos** [comment] 2017-06-07 12:54
I am closing this issue because it is not reproducible. Feel free to reopen if you can provide us with a small app reproducing the problem (see [Bug reporting instructions](http://loopback.io/doc/en/contrib/Reporting-issues.html#bug-report)).

**Closed by bajtos** 2017-06-07 12:54 UTC
