### ISSUE TITLE
$save not working with foreign key to user table when include is done on previous GET.

### ISSUE THREAD

**Issue by alexxgathp** [strongloop/loopback-sdk-angular#119] opened 2015-01-12 20:44 UTC
**The Problem**: For some reason, under the following conditions, a foreign key attribute linking to the user table's user id does not update when using $save in a function linked to a button. 
Using Mozilla Firebug, I am not getting any error response. However, if the button running the "release" function, which is setting the user id value to null in the "reservedby" attribute, is pressed twice in a row, then it works. Running the function twice with one press does not work. Also, if I remove from the filter being passed  

``` javascript
"include: ['user ' " // Removing this part of the filter with the include
```

 from the original find() or GET function, it works, but then, I cannot display user details.  

Any ideas?

Here are some more details:

I am using the Loopback AngularJS SDK architecture.

I have a MySQL table called "servers" and use the "users" table, which has a model called Serveruser which extends the Loopback user model.
There is a foreign key belongTo relationship between "servers" and "users". The default empty value for "reservedby" is null.
The Serveruser model also has a hasMany relationship defined in it.

**controller.js**

``` javascript
$scope.filtered = { filter: { include: ['user', //etc
Servers.find($scope.filtered)... //etc 
// Later in the code
  $scope.release = function (server) {

          server.reservedby = null;
                server.$save()
            .then(function(result) {
              console.log('Release result!');
              console.log(result);
          });
      };
```

**Serveruser.json**

``` javascript
{
    "name": "serveruser",
    "base": "User",
    "options": {
        "mysql": {
    "table": "user"
  }
    },
    "dataSource": "test_mysqldb",
    "properties": { },
    "validations": [ ],
    "relations": {
        "accessTokens": {
            "model": "accessToken",
            "type": "hasMany",
            "foreignKey": "userId"
        },
        "serverses": {
            "model": "servers",
            "type": "hasMany",
            "foreignKey": "reservedby"
        }

        },
  "acls": [
    {
      "accessType": "READ",
      "principalType": "ROLE",
      "principalId": "$authenticated",
      "permission": "ALLOW"
    }
  ],
  "methods": []
}
```

In the **Servers.json**

``` javascript
    "reservedby": {
      "type": "Number",
      "required": false,
      "length": null,
      "precision": 11,
      "scale": 0,
      "mysql": {
        "columnName": "reservedby",
        "dataType": "int",
        "dataLength": null,
        "dataPrecision": 11,
        "dataScale": 0,
        "nullable": "YES"
      }
}
// Later in the model JSON file

"relations": {
    "user": {
        "type": "belongsTo",
        "model": "serveruser",
        "foreignKey": "reservedby"
    }
}
```

This might relate to issue #70 , as I sometimes get that error code under a slightly different set of conditions.

**Comment by superkhau** [comment] 2015-01-12 22:49
@alexxgathp Thanks for the report. Will try to reproduce.

**Comment by alexthewilde** [comment] 2015-06-10 04:26
+1

**Comment by alexxgathp** [comment] 2015-06-13 19:59
I may have an explanation for the issue, though I haven't checked it recently since I had to design around it at the time.
It happened with several other models, a save not saving when changing the id while using an include.

I finally got those $save to work by changing both the id field and the included instance. 
For instance, say there is a testid, I do a include: "test".
I would change both the object.testid and object.test.
Object.test I would get by doing Test.findOne() with the where filter as the object.testid.

Though inefficient, it seemed to work. It seems like an overall design flaw of some sort.

**Comment by superkhau** [comment] 2015-11-30 23:00
@alexthewilde Can you provide a link to a test project with steps to reproduce the issue? See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.

**Comment by superkhau** [comment] 2015-11-30 23:01
@chandadharap Taking out of TOB because this issue is not fully triaged yet. Adding major label also to make sure we look at it.

**Comment by superkhau** [comment] 2016-02-03 02:49
@0candy Reassigning to you since you are the repo expert now.

**Comment by davidcheung** [comment] 2016-06-14 19:22
Hi @alexxgathp, 
I'm going to attempt to describe the issue, can you let me know if this describes the issue?

- Query w/ `include filter`(relationship linked via `foreignKey`)
- update one of the instance 
- `include filter` lost

would you know if it only happens when specified foreign key is used?

**Comment by bajtos** [comment] 2017-06-07 13:13
I am closing this issue because it's not clear how to reproduce it.

**Closed by bajtos** 2017-06-07 13:13 UTC
Labels: triaging
