### ISSUE TITLE
Upsert shouldn't  set url?

### ISSUE THREAD

**Issue by MikeSpock** [strongloop/loopback-sdk-angular#130] opened 2015-03-03 10:25 UTC
There is an issue when updating an existing resource:

    $scope.user = User.findById({ id: $state.params.id });
        
    $scope.submit = function(){
        $scope.user.$save().then(function() {
            $state.go('userList');
        });
    }

Then backend throws an error, because the sent request goes to the url '?id=xx', due to the fact, that upsert is misconfigured. Requested uri is: `http://my-machine/api/User?id=2`

    "upsert": {
        url: urlBase + "/User",
        method: "PUT"
    }

`url: urlBase + "/User"` should contain `:id`, or remove the url line and use defaults set in the top of the type declaration.

**Comment by bajtos** [comment] 2015-03-04 08:27
Closing as a duplicate of #125.

**Closed by bajtos** 2015-03-04 08:27 UTC
