### ISSUE TITLE
LoopBackAuth.rememberMe is not maintained after reloading page

### ISSUE THREAD

**Issue by brunoporto** [strongloop/loopback-sdk-angular#118] opened 2015-01-07 20:44 UTC
When you logIn with rememberMe =  true, and refresh page you lose that true causing the script
https://github.com/strongloop/loopback-sdk-angular/blob/71e24c656c0f4b303cb897e77a8ef6471001af74/lib/services.template.ejs#L269

always try to clear the "sessionStorage", so you must also save the rememberMe in any of the storage so it can be recovered.

To test do the issue:
- Log in to remember = true
- Reload the page
- Log out

You will see that in "localstorage" you have your token and id.

**Comment by nolandubeau** [comment] 2015-01-07 20:52
I just verified this as well using the latest version of strongloop and the angular generated services.  I did a fresh install today.

**Comment by csvan** [comment] 2015-06-22 00:04
Confirming this. Remember Me is currently useless due to this.

**Comment by johannesjo** [comment] 2016-01-22 16:58
This is still an issue for me using loopback@2.26.2

**Comment by davidcheung** [comment] 2016-01-27 19:29
Reopening issue to troubleshoot. 
@johannesjo can you describe how is it failing for you?  or steps to reproduce your scenario. 
and please note that the behavior currently for `rememebrMe` is `undefined` reoslve as `true` to preserve backwards compatibility.

**Comment by johannesjo** [comment] 2016-01-27 20:03
Actually it turned out to be a misconfiguration in my router module, which was not properly checking for a logged in user. Sorry for trouble.

**Comment by davidcheung** [comment] 2016-01-27 20:39
@johannesjo haha no problem, closing issue :)

**Closed by davidcheung** 2016-01-27 20:39 UTC
Labels: bug

**Comment by dev-augmenta** [comment] 2016-02-01 11:25
Actually the bug is still there. The auto generate lb-services.js for the User.login function is checking the "rememberMe" param in response.config.params while it should be in response.config.data.

If your are controlling session, login and access via Angular, change the User.login to this
 
LoopBackAuth.rememberMe = response.config.data.rememberMe !== false;

**Comment by davidcheung** [comment] 2016-02-01 14:28
@dev-augmenta, Thanks for bringing this up, I believe this is done to preserve the behavior before where `rememberMe = false` was added as an option. I do agree this brings confusion for the users, maybe we could look to change the default in a major release. The current behavior is [documented here](https://apidocs.strongloop.com/loopback-sdk-angular/#user-login).

/cc @bajtos any thoughts?
