### ISSUE TITLE
namespacing LoopBackResource and LoopBackAuth

### ISSUE THREAD

**Issue by nidhhoggr** [strongloop/loopback-sdk-angular#192] opened 2015-11-21 02:27 UTC
Is there a way you can provide an option in the lb-service.js generator to namespace the angular services mentioned in the title. The issue is that I have a client that is dependent on multiple loopback API's and therefore requires multiple lb-services for DI in my angular app config. The AppAuth and other services are clashing. As of now I have to manually rename all of the services and modules after I generate them. Thanks.

**Comment by davidcheung** [comment] 2015-11-23 14:47
Not sure if this is what you were looking for, the [`lb-ng` command](https://docs.strongloop.com/display/public/LB/AngularJS+JavaScript+SDK#AngularJSJavaScriptSDK-lb-ngcommand)  does have a feature to pass a module-name, if I misunderstood you please clarify, thanks!

**Comment by zmijevik** [comment] 2015-11-23 19:40
It seems like this command accounts for the module name but not the service name or providers. According to angular documenation, there is no feature to prevent from service/provider name from clashing with other modules that contain the same service or provider name.

**Comment by bajtos** [comment] 2016-11-09 13:21
Closing as a duplicate of #250

**Closed by bajtos** 2016-11-09 13:21 UTC
Labels: feature
